version: '3.8'

services:
  app_im:
    build: ./
    command: ./shortenLink
    ports:
      - "8080:8080"
  app_db:
    build: ./
    command: ./wait-for-postgres.sh db ./shortenLink -db
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=ghjghj

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ghjghj
    ports:
      - "5432:5432"
  migration:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - .:/migrations
    command: ["user=postgres password= ghjghj dbname=postgres sslmode=disable", "up"]
    links:
      - db
    depends_on:
      - db
networks:
  new:
